wandb_version: 1

wd:
  desc: null
  value: 0.03
patch_size:
  desc: null
  value: 16
model_name:
  desc: null
  value: vit_base
batch_size:
  desc: null
  value: 128
warmup:
  desc: null
  value: 20
lr:
  desc: null
  value: 0.0012
_wandb:
  desc: null
  value:
    python_version: 3.9.18
    cli_version: 0.16.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: true
    start_time: 1711616222.0
    t:
      1:
      - 1
      - 41
      - 55
      - 105
      2:
      - 1
      - 41
      - 55
      - 105
      3:
      - 16
      - 23
      4: 3.9.18
      5: 0.16.5
      8:
      - 2
      - 5
      - 9
      13: linux-x86_64
